server:
  port: 8081

spring:
  application:
    name: friday-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://112.124.30.60:3306/friday
    username: root
    password: 123456



